org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-modules java.base/sun.security.provider --add-modules java.base/sun.security.util --add-opens java.base/sun.nio.ch=ALL-UNNAMED --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
kotlin.jvm.target.validation.mode=warning
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
systemProp.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
// Force Java system properties to bypass environment variables
systemProp.java.version=17
systemProp.java.runtime.version=17